### ISSUE TITLE
Fix: Service Gordon(Bare) not starting

### ISSUE THREAD

**Issue by MatteoBuriola** [EOS-Solutions/Gordon#103]
The service Gordon Service (BARE) fail to start.
In the event viewer i find the following error:

Category: Microsoft.Extensions.Hosting.Internal.Host
EventId: 11
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Hosting failed to start

Exception: 
System.Net.Sockets.SocketException (10013): Tentativo di accesso al socket con modalità non consentite dalle rispettive autorizzazioni di accesso.

-  Gordon Powershell (1.1.14)
-  Bare.WebApi (3.0.19)

**Comment by Stefano-Primo-EOS** [comment]
Is this a new installation? 
Have you uninstalled NVT Remote first? 
Gordon Service is running with a certain user? Does it have all the necessary permissions?

**Comment by MatteoBuriola** [comment]
I uninstalled Smeagol NVT Remote and now the service is working.
