### ISSUE TITLE
[Xliff editor] feat: allow remove multiple languages

### ISSUE THREAD

**Issue by Luca-Maritano-EOS** [EOS-Solutions/Gordon#105]
# 🙋 Feature Request

Remove multiple languages simultaneously.

## 🤔 Expected Behavior

Click on "Remove Language"
Select the languages that you want to remove
Click ok to remove the languages

## 😯 Current Behavior

It's possible to remove only one language at a time.

## 💻 Examples

![image](https://github.com/user-attachments/assets/973769de-027d-43a2-a20a-52111fa63625)

## Product
- Gordon XLIFF Editor 3.0.29.0

**Comment by Thomas-Torggler-EOS** [comment]
Available in 30.0.30
