### ISSUE TITLE
EOS Gordon Installer - Situazione app non corretta

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#107]
# 🐛 Bug Report
Disinstallando le app dal vecchio EOS Installer (non più presenti a sistema) nel nuovo EOS Gordon Installer risultano ancora installate.

### Errore
EOS Installer
![image](https://github.com/user-attachments/assets/312fe326-ddf8-4c1d-9c51-497784b89366)

EOS Gordon Installer
![image](https://github.com/user-attachments/assets/489acdef-ad79-4fc2-8525-e0bbe18694ab)

### Work around
Andando nel file registry e cancellando i riferimenti alle app disinstallate sono di nuovo disponibile dal nuovo installer

![image](https://github.com/user-attachments/assets/0fa1dad5-2922-46ba-86f6-2a30df49b149)

![image](https://github.com/user-attachments/assets/8ee2cc89-0be0-4eea-a46c-07228e7d2d64)

![image](https://github.com/user-attachments/assets/82c6989d-210d-4bc0-bab2-0472002a16d3)

**Comment by Thomas-Torggler-EOS** [comment]
Serve qualche dettaglio in più, non sono sicuro di aver' capito:

> Disinstallando le app dal vecchio EOS Installer 
Usando cosa? Il veccio o il nuovo?

> (non più presenti a sistema) 
Non lo erano già quando le hai disinstallate? Li hai cancellati a mano?

> nel nuovo EOS Gordon Installer risultano ancora installate.
Il nuovo installer migra lo stato delle app dal vecchio la prima volta che parte. Da questo punto in poi la vecchia registry non la guarda più.

**Comment by alessiopellindgm** [comment]
Buongiorno.

> > Disinstallando le app dal vecchio EOS Installer
> 
> Usando cosa? Il veccio o il nuovo?
> > (non più presenti a sistema)
> 
> Non lo erano già quando le hai disinstallate? Li hai cancellati a mano?

Qualche giorno fa ho disinstallato le app attraverso il vecchio "Eos Installer".
Oggi ho installato il nuovo "EOS Gordon Installer" e provato ad installare i programmi da li con i problemi sopra descritti.

> > nel nuovo EOS Gordon Installer risultano ancora installate.
> 
> Il nuovo installer migra lo stato delle app dal vecchio la prima volta che parte. Da questo punto in poi la vecchia registry non la guarda più.

Confermo. Verificando su un altro PC, al primo update di un programma dal nuovo installer, quest'ultimo rimane aggiornato con la versione corretta del programma.

**Comment by Thomas-Torggler-EOS** [comment]
Più che essere "EOS Gordon Installer" ad avere le versioni non corrette direi che è il vecchio "EOS Installer" a non aver' fatto bene l'unistall. Poi con la migrazione della registry "EOS Gordon Installer" ha migrato questa registry errata. L'uninstall aveva spesso problemi su "EOS Installer".
