### ISSUE TITLE
[Gordon XLIFF Editor] Fix: Save doesn't work when provider database is enabled

### ISSUE THREAD

**Issue by Luca-Maritano-EOS** [EOS-Solutions/Gordon#108]
# 🐛 Bug Report

When the provider Database is enabled, saving new translations doesn't work

## 💻 Repro

1. Insert a Database provider (Connection string Server=BR-LABSSQL1\SQL2016;Database=XliffEditor2_0)
(The default Connection string Server=(localdb)\mssqllocaldb;Database=XliffEditor works even if the DB doesn't exist)
3. In the editor change a caption
4. Save

## 🤔 Expected Behavior

Save

## 😯 Current Behavior

The save doesn't work, disabling the provider allows to save the translations.

## Product
- [ X] Gordon XLIFF Editor 3.0.32.0

**Comment by Thomas-Torggler-EOS** [comment]
A new version (3.0.33) will soon be available. This will most probably not fix the issue, but at least it will not impede saving of the project in case of an error.

Also, a log is now written in case a provider fails to save it's context. This file is located in `%appdata%\EOS Solutions\XLIFF\debuglog.txt`. Can you please try again and post the error you get to help finding the cause? Thanks.

**Comment by Luca-Maritano-EOS** [comment]
I've updated the XLIFF editor and the saving correctly works.

I've encountered 2 errors:
- Host unreachable (while I was not in VPN)
`2024-09-25T12:15:15.3998534+02:00	FAIL	[Gordon.XliffEditor.Providers.DatabaseProvider]	[0]	Saving context of provider 3b5b18cd-8472-4d81-9788-0f03c0cbcb10 failedMicrosoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)`

- The certificate chain was issued by an authority that is not trusted (with VPN activated)
`2024-09-25T12:18:59.5513971+02:00	FAIL	[Gordon.XliffEditor.Providers.DatabaseProvider]	[0]	Saving context of provider 3b5b18cd-8472-4d81-9788-0f03c0cbcb10 failedMicrosoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)`

I attach the full file
[debuglog.txt](https://github.com/user-attachments/files/17129278/debuglog.txt)

**Comment by Thomas-Torggler-EOS** [comment]
> Host unreachable (when I was not connected to the VPN)

Not really much I can do :)

> The certificate chain was issued by an authority that is not trusted (with VPN activated)

I've seen this before (EOS Function API for example). Never really found out what exactly is causing the certificate chain failure. However: you can bypass this by modifying the connection string:
https://learn.microsoft.com/en-us/troubleshoot/sql/database-engine/connect/certificate-chain-not-trusted?tabs=ole-db-driver-19
