### ISSUE TITLE
Fix: Multiple in Gordon

### ISSUE THREAD

**Issue by Stefano-Primo-EOS** [EOS-Solutions/Gordon#110]
# 🐛 Bug Report

- [x] Last used services: if there isn't any, write "No last used"
- [x] Container/Service: Consolidate Action and Grid Action (image 1)
- [x] Edit Server: Create URI after save, make fields only strings
- [x] SaasTenant: Keep TenantId and Description
- [x] EditForms: Set Required Fields
- [x] ServiceApps: From Tenant use only first char of guid
- [x] OpenInWebClient: If BaseUrl empty --> Warning
- [x] ServiceApps: Add Unpublish with Delete Data
- [x] Add Help URLs

Image 1
![image](https://github.com/user-attachments/assets/4b6386fe-80d4-489a-9d5d-aa3f1ef7f121)

**Comment by AndreaDiCeglie** [comment]
Edit Server: suggest "http" as syntax
Rename Global Settings in user settings
user settings: 
    - move all docker default at the end
    - Default license path -> Default license file and path (suggest c: \temp\mylicense.bclicense
    - Group all defaults and set Defaults only in group title
    
    - Add tooltip to key fields , especially in setups
    
    Service app matrix:
    - Limit matrix in view only mode to 3-4 enviroment
    - Let install-update single app only to many environment (select single app, then select environments...)
    
Container wizard
 - Default license path -> Default license file and path (suggest c: \temp\mylicense.bclicense
 - Add property Accept EULA for preview

**Comment by Stefano-Primo-EOS** [comment]
Work in progress
Missing: 

- [ ]  Container/Service: Consolidate Action and Grid Action (image 1)
- [ ] ServiceApps: Add Unpublish with Delete Data
- [ ] Add tooltip to key fields , especially in setups
- [ ] Service app matrix: Limit matrix in view only mode to 3-4 environment. Let install-update single app only to many environment (select single app, then select environments...)
- [ ] Add property Accept EULA for preview
- [ ] Container name is requested during script execution (asked twice)

**Comment by Stefano-Primo-EOS** [comment]
#116
