### ISSUE TITLE
[VSCode Gordon] Gordon build and other functions doesn't work when there is a file Settings.json in .vscode folder

### ISSUE THREAD

**Issue by Luca-Maritano-EOS** [EOS-Solutions/Gordon#113]
# 🐛 Bug Report
Gordon build and other functions doesn't work when there is a file Settings.json in .vscode folder.

## 💻 Repro

- Open an app
- add file settings.json in .vscode folder
- Try to build with gordon (error 1)
- add an empty object o a line to the  json object
- Try to build with gordon (error 2)

## 🤔 Expected Behavior

Build

## 😯 Current Behavior

Error

## 📸 Screenshots
Error 1:
![image](https://github.com/user-attachments/assets/d1c81f38-ecc8-41f9-844c-2aba635303c7)

Error 2:
![image](https://github.com/user-attachments/assets/bd349239-aead-49a3-b3af-ea477efb1ed0)

## Product
- Gordon VSCode 0.1.41

**Comment by Thomas-Torggler-EOS** [comment]
Available in 0.1.45
