### ISSUE TITLE
[Gordon Xliff Editor] feat: add the "issue?" button in the bottom left corner like in gordon

### ISSUE THREAD

**Issue by Luca-Maritano-EOS** [EOS-Solutions/Gordon#114]
# 🙋 Feature Request

Add the "issue?" button in the bottom left corner like in gordon

## 💻 Examples

![image](https://github.com/user-attachments/assets/3b1a938b-f005-4a8a-8ee1-ae33aef4e084)

## Product
- Gordon Xliff Editor 3.0.33

**Comment by Thomas-Torggler-EOS** [comment]
Done.
