### ISSUE TITLE
[Gordon Xliff Editor] Sequence order of providers is not used

### ISSUE THREAD

**Issue by Luca-Maritano-EOS** [EOS-Solutions/Gordon#115]
# 🐛 Bug Report

The auto-translate feature doesn't use the sequence order.

## 💻 Repro

1. Add multiple providers.
2. Specify a sequence different from the sorting order.
3. Try to auto-translate (the provider list is presented in insert order and not in sequence order)
4. The translation is proposed from the first of the list

## 🤔 Expected Behavior

Auto-translate must use sequence order.

## 😯 Current Behavior

Auto-translate uses insert order.

## 📸 Screenshots
![image](https://github.com/user-attachments/assets/fa094ffb-32ce-4e03-a8ad-2327a7931f40)

![image](https://github.com/user-attachments/assets/a3ee6ff9-4c5f-4986-8aa7-d961270ed139)

![image](https://github.com/user-attachments/assets/e157132e-de44-4778-bace-65f976e18ca5)

![image](https://github.com/user-attachments/assets/5169c4ce-5ecf-4c59-afdc-9882e0fa5bdf)

## Product
- [X] Gordon Xliff Editor 3.0.33.0

**Comment by Thomas-Torggler-EOS** [comment]
Actually, it already worked correctly - sort of.

"0" is treated as "not-ordered". When using auto-translate, it first takes all ordered providers (> 0) and then all the unordered ones (<= 0). This is because 0 is the default value.

This has now been changed and 0 is now also ordered correctly.
