### ISSUE TITLE
Fix: Double EOS Gordon Installer

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#121]
# 🐛 Bug Report
I have two versions of EOS Gordon Installer in my PC with two different versions and two methods to install the same application.

## 💻 Repro
In the EOS Gordon Installer, installed from Microsoft Store, appeared new item, to a more recent version, of the EOS Gordon Installer application.
![image](https://github.com/user-attachments/assets/27c6c4cb-c11a-4047-a7f1-8ca63a26898c)

After installing it, I have two versions of EOS Gordon Installer in my PC with two different versions:
- the version installed from Microsoft Store at 0.0.95 (the available version)
- the version installed from "EOS Gordon Installer" at 0.0.104
![image](https://github.com/user-attachments/assets/8334868a-8c04-4167-a16a-866605ce5420)

## Product
- [ ] Gordon (Version: 1.1.23.0)
- [ ] Gordon Powershell (Version: ###)
- [ ] Gordon Service (Version: 3.0.22)
- [ ] Gordon Xliff Editor (Version: 3.0.36)
- [X] EOS Gordon Installer (Version: 0.0.103)

**Comment by Stefano-Primo-EOS** [comment]
You found a newer version of the Gordon Installer. 
Now, what you can do? From now on, you can uninstall the "Store" version of the Installer and use only the one installed by the installer. 
What's changed? nothing, but in the near future we will stop provide the Gordon Installer from the MS Store!
