### ISSUE TITLE
Fix: Update Available in Gordon 1.1.24.0

### ISSUE THREAD

**Issue by Daniele-Corona-EOS** [EOS-Solutions/Gordon#122]
In a BC24 environment the client already has the BC22 extensions installed, Gordon does not list the extensions to update that refer to the BC24 feed

## Product
- [x] Gordon (Version: 1.1.24.0)

**Comment by Stefano-Primo-EOS** [comment]
Can you elaborate a bit more and also add some screenshot?

**Comment by Daniele-Corona-EOS** [comment]
I have a BC24 OnPrem environment migrated from BC22 where BC22 apps are still present; I expect that when I search for app updates, the list of installed apps that can be updated to BC24 will appear.
Here are the images
![2024-10-04 17_38_07-tsnavbc eos it - Remote Desktop Connection](https://github.com/user-attachments/assets/a400e401-113b-4255-9650-b458355ae7a5)
![2024-10-04 17_39_07-tsnavbc eos it - Remote Desktop Connection](https://github.com/user-attachments/assets/0c8e7796-c93a-442e-aa77-4f66dd4f34da)
![2024-10-07 17_37_20-tsnavbc - tsnavbc eos it - Remote Desktop Connection](https://github.com/user-attachments/assets/08531547-547a-4415-9019-9ac62b569607)
