### ISSUE TITLE
Error: Response status code does not indicate success: 401 (Unauthorized) when i try tu use nuget feed

### ISSUE THREAD

**Issue by Giuliano-Velludo-EOS** [EOS-Solutions/Gordon#123]
# 🐛 Bug Report
Error: Response status code does not indicate success: 401 (Unauthorized) when i try tu use nuget feed

[debug.txt](https://github.com/user-attachments/files/17278837/debug.txt)

## 📸 Screenshots

This is the feed (i tried also with https):
![image](https://github.com/user-attachments/assets/85741f0f-3018-4fa9-90ca-720a6df06882)

## Product
- [ ] Gordon (Version: 1.1.24.0)

**Comment by Stefano-Primo-EOS** [comment]
Resolved as it was a permission related to the User vs the Feed
