### ISSUE TITLE
[Gordon VSCode] Fix: doesn't work with cointainers with SSL enabled

### ISSUE THREAD

**Issue by Luca-Maritano-EOS** [EOS-Solutions/Gordon#134]
# 🐛 Bug Report

I have a container with SSL enabled.
Running every command from Gordon VSCode returns the error:
The SSL connection could not be established, see inner exception.
![image](https://github.com/user-attachments/assets/182f2c19-9e0e-47e1-ae36-c982e36e3fc1)

## Product
- Gordon VSCode Version: 0.1.52

**Comment by Thomas-Torggler-EOS** [comment]
Resolved in 0.1.53
