### ISSUE TITLE
Fix: Service Status in Gordon

### ISSUE THREAD

**Issue by Paolo-Visenti-EOS** [EOS-Solutions/Gordon#135]
The Service Status between Smeagol and Gordon is not the same

## 📸 Screenshots
![image](https://github.com/user-attachments/assets/667494ce-dfb2-4bde-ae63-dca7147d2973)

## Product
- [ ] Gordon (Version: 1.1.24.0_)
- [ ] Gordon Powershell (Version: _WriteHereTheVersion_)
- [ ] Gordon Service (Version: _WriteHereTheVersion_)
- [ ] Gordon Xliff Editor
- [ ] EOS Gordon Installer

**Comment by Stefano-Primo-EOS** [comment]
On the page "Docker Container" in Gordon, you will see the containers and their relative statuses. 
Smeagol, instead, will look into the Service (it doesn't know if they are servers or container) and see the status of the  BC service. 

If you, in gordon, from the docker container, click on the action "Services" you will see the same as gordon and that is: 

Your container is running, the BC service does not.

**Comment by Paolo-Visenti-EOS** [comment]
Scusa Stefano.
Chiaro
Lunedì c'è il workshop di Gordon
Starò molto attento...
Grazie mille


Paolo Visenti
BC Senior Developer
EOS Solutions
Mail + Teams: ***@***.***
P:+390499249000 | Mob: +39 3482340488
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.
