### ISSUE TITLE
feat: Gordon Installer - Add install Function API as a service

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#139]
# 🙋 Feature Request
Installing Function API from Gordon Installar doesn't create a service like installing from Smeagol.
This is essential when installing Function API on server.
This feature should only be active Machine-wide.

## 🤔 Expected Behavior
Gordon Installar create a Function API service automaticaly.

## 😯 Current Behavior
Gordon Installar installs Function API but it must be launched manually.

## Product
- [X] EOS Gordon Installer (Version: 0.0.114)

**Comment by Thomas-Torggler-EOS** [comment]
Available in 1.0.134
