### ISSUE TITLE
Fix: Gordon Installer update error.

### ISSUE THREAD

**Issue by Daniele-Corona-EOS** [EOS-Solutions/Gordon#142]
# 🐛 Bug Report
Problems downloading and updating Gordon from Gordon Installer.

## 💻 Repro
I run Gordon installer as administrator to be able to update Gordon Machine-wide.

## 🤔 Expected Behavior
Gordon's update as already done for other previous versions.

## 😯 Current Behavior
Returns error message

## 📸 Screenshots
![image](https://github.com/user-attachments/assets/efb16279-db98-4c8b-aebf-3b81288f5cba)

## Product
- [x] EOS Gordon Installer (0.0.115.0)

**Comment by Stefano-Primo-EOS** [comment]
Could you send us a zip with the logs? 
You can find it in: "%localappdata%\Programs\EOS Solutions\.logs"

**Comment by Daniele-Corona-EOS** [comment]
[gordon-installer.log](https://github.com/user-attachments/files/17432181/gordon-installer.log)
[gordon-installer-deploy.log](https://github.com/user-attachments/files/17432182/gordon-installer-deploy.log)

**Comment by Daniele-Corona-EOS** [comment]
I have tried today and now it’s working.

**Comment by Thomas-Torggler-EOS** [comment]
🚀
