### ISSUE TITLE
Fix: Gordon installer don't see Gordon Service in Docker

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#143]
# 🐛 Bug Report
Gordon Installer don't see Gordon service installed in docker machine even if it is installed.
![image](https://github.com/user-attachments/assets/a8265afa-226a-44ff-a310-f6006b0e2d80)

## 💻 Repro
I try to install Gordon Service in these ways but the result is the same:

1. Use script generate with Gordon (create container & install gordon service)
2. Use Gordon Service
 -- Select Scope a local docker
 -- Install Gordon Service

## Product
- [X] Gordon (Version: 1.1.34.0)
- [X] Gordon Service (Version: 3.0.22)
- [X] EOS Gordon Installer (Version: 0.0.115)

**Comment by Stefano-Primo-EOS** [comment]
Do you remember if Gordon Service was installed via gin or from previous version of the script?

**Comment by alessiopellindgm** [comment]
I installed it via gin (on 10/10/24)

**Comment by Thomas-Torggler-EOS** [comment]
You should have the following folder on your machine: `%programdata%\BcContainerHelper\Extensions` where there should be a subfolder for each of your containers. In the folder of your container you should have the subfolder `my\programs\machine`. 
- Do you see "bare.webapi" there as the folder?
- There should be a folder ".logs" and a file ".registry". Can you attach them here?
- Please PowerShell into your container (`Open-BCContainer <containerName>`) and then run the following script. What is the output?
  `Get-WmiObject win32_service | ?{$_.Name -ieq 'bare.webapi'} | select Name, DisplayName, State, PathName`

**Comment by alessiopellindgm** [comment]
> * Do you see "bare.webapi" there as the folder?

No, don't exist.

> * There should be a folder ".logs" and a file ".registry". Can you attach them here?

In .logs folder is this file. [bare.webapi.log](https://github.com/user-attachments/files/17474605/bare.webapi.log)
Not exist ".registry" file.

> * Please PowerShell into your container (`Open-BCContainer <containerName>`) and then run the following script. What is the output?
>   `Get-WmiObject win32_service | ?{$_.Name -ieq 'bare.webapi'} | select Name, DisplayName, State, PathName`

```shell
[FIN-PROD-24-5] PS7 C:\Run> Get-WmiObject win32_service | ?{$_.Name -ieq 'bare.webapi'} | select Name, DisplayName, State, PathName
Get-WmiObject: The term 'Get-WmiObject' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by Thomas-Torggler-EOS** [comment]
I have some more questions.

- What version of gin.exe were you using to install? Please run a `gin.exe --version`.
- The error you get in the container is a PowerShell error. Not sure why that won't run on your machine, runs fine on mine and on my contains on PS5 and PS7. But it makes little difference. What I really need to know is: where exactly (inside the container) is your Gordon Service located? The service that is running, where does it point to?

**Comment by alessiopellindgm** [comment]
```shell
>./gin.exe --version
gin 0.0.115+63112acf314bb4f0027c8fbd737a03304a87b476
``` 

In this container Gordon service located in 'C:\ProgramData\Programs\EOS Solutions\' and I see this strutcure
![image](https://github.com/user-attachments/assets/1f71c6c2-189f-4117-b3f2-f6538b5b0deb)

These are the files present in the folder present in the container:
in root (rename .registry because github not upload "hidden" file)
[registry.txt](https://github.com/user-attachments/files/17476497/registry.txt)

in .logs
[bare.webapi-deploy.log](https://github.com/user-attachments/files/17476484/bare.webapi-deploy.log)

**Comment by Thomas-Torggler-EOS** [comment]
Looks like you have used gin to install **into** the container from **inside** the container. While this technically works (as you see your service is running) you then also need to manage this installation from **inside** the container and cannot use Installer UI (or gin.exe even) **outside** the container.

The idea however is, that never install anything from **inside** the container. The installer UI as well as gin.exe are meant to be run **outside** the container.

**Comment by Thomas-Torggler-EOS** [comment]
Or at least something is happing that makes your container appear to the installare as not being a container.

- Can you provide the exact script that you used to create the container?
- Can you provide list of all environment variables that are available **inside** the container?

**Comment by alessiopellindgm** [comment]
This is install script [1_FIN_PRODBC24_DockerDBSQL_241010.txt](https://github.com/user-attachments/files/17476931/1_FIN_PRODBC24_DockerDBSQL_241010.txt)

environment variables [ENV_FIN-PROD-24-5.txt](https://github.com/user-attachments/files/17476995/ENV_FIN-PROD-24-5.txt)

**Comment by alessiopellindgm** [comment]
Today I tried to create another container without running gin to install the Gordon service and launched the installation with Gordon Installer.

These are the errors.
![image](https://github.com/user-attachments/assets/870a6cfd-77dc-408c-99cd-7c88f4479253)


These are log files
[gordon-installer.log](https://github.com/user-attachments/files/17490061/gordon-installer.log)
[gordon-installer-deploy.log](https://github.com/user-attachments/files/17490062/gordon-installer-deploy.log)

**Comment by Thomas-Torggler-EOS** [comment]
We have pushed a new update to the installer today. I see you are now using 0.0.116 which is the latest one available 😊

There are multiple things at play here:

1) This new version resolves a problem where it did not correctly detect containers. This problem is the reason for your original issue. That is: you installed "Gordon Service" but then it is not visible to the Installer. This happened because it was installed in the wrong folder / registry. To resolve this, you should (manually) remove the service and it's files and the try to install it again with version 0.0.116. Or recreate the container and try again.

2) 'Access denied error' is a different issue. I have tried locally and I cannot replicate. Are you using HyperV? I know that HyperV does sometimes locks files **inside** the container and causes problems. Usually restarting the container helps. Unfortunately there's not much we can do about that.

In any case `gin.exe` or the installer UI are using the same method of installing. There should be no difference in using one or the other.

**Comment by alessiopellindgm** [comment]
Ok. Tomorrow I try to create new container with HyperV option.

**Comment by alessiopellindgm** [comment]
I created the containers with HyperV but it still gives previous error during Gordon service installation as above.

**Comment by Thomas-Torggler-EOS** [comment]
Plase open a new issue for this problem as the original issue has been resolved and this is a different one.
