### ISSUE TITLE
Help: FunctionAPI Log folder

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#144]
# 🚑 Help Request
The last version of Function API doesn't have the option to select a log folder.

Old Version (1.0.84)
![image](https://github.com/user-attachments/assets/6b410948-70c3-4190-9756-22383c409b9c)

New version (1.0.132)
![image](https://github.com/user-attachments/assets/f58c407f-ecd1-4baf-ad24-ad7bbc02a9c9)

In the API configuration you can select the "EnableLog" option
![image](https://github.com/user-attachments/assets/d0e9b286-b2f4-44ae-ad7d-014652b9fb55)

- How do they work in the new version?
- Where are the logs saved?

**Comment by Stefano-Primo-EOS** [comment]
From a few versions ago, FunctionAPI will only support Application Insights for logging, Folder support is no longer maintained.

**Comment by alessiopellindgm** [comment]
I ask you some info since I am not an expert on Azure Application Insights.
I see that the field must contain a specific key...
Is the FunctionAPI configured to send logs only to EOS Azure servers?
Is there a possibility of having details on the logs structure so that we can manage the data that arrives on Application Insights from our customers or development environments?
