### ISSUE TITLE
some small change requests 

### ISSUE THREAD

**Issue by Stefano-Papa-EOS** [EOS-Solutions/Gordon#147]
# 🙋 Feature Request

Some small change requests to improve Gordon app

## 🤔 Expected Behavior and 😯 Current Behavior
- dimensionamento finestra: quando apro l'app è sempre a schermo intero, vorrei che mantenesse il dimensionamento che aveva all'ultimo utilizzo
- Action synch: dopo che utilizzo l'action, la/le app vengono sempre deselezionate, vorrei mantenesse la selezione per non dover riselezionarle
- dimensionamento colonne: vorrei fosse possibile che con doppio click la colonna prenda la dimensione uguale alla lunghezza massima del testo presente in quella colonna

![image](https://github.com/user-attachments/assets/05177a4f-d591-4ec6-bcad-760e9d2daf39)

- shortcut selezione: vorrei che con shift + click si possano selezionare tutte le righe da quella selezionata a quella su cui è il cursore 

![image](https://github.com/user-attachments/assets/2a6a9a29-c4b5-4cb8-9768-f4eca68854dd)

- hide ms app flag: vorrei si potesse selezionare/deselezionare solamente quando il cursore è sopra il flag, al momento anche se è sulla stessa 'direzione' lo attiva/disattiva. Mi capita di cliccare erroneamente sullo spazio bianco e vorrei evitare un update senza motivo delle app.

![image](https://github.com/user-attachments/assets/c4ab2c88-d4c5-485f-af57-155b1498735b)

## Product
- Gordon WebApp (Version: 1.1.34.0)

**Comment by Stefano-Primo-EOS** [comment]
> dimensionamento finestra: quando apro l'app è sempre a schermo intero, vorrei che mantenesse il dimensionamento che aveva all'ultimo utilizzo

questo si può fare

> Action synch: dopo che utilizzo l'action, la/le app vengono sempre deselezionate, vorrei mantenesse la selezione per non dover riselezionarle

Il problema di questo è che quando si fanno operazioni con le app, al 99% è necessario aggiornare la lista (specialmente prendendo i dati dal servizio), cambiando i dati, cambiano anche i riferimenti alle app. Però: quale azioni compi che ti serve selezionare più volte le stesse app? magari si possono accorpare delle azioni!

> dimensionamento colonne: vorrei fosse possibile che con doppio click la colonna prenda la dimensione uguale alla lunghezza massima del testo presente in quella colonna

Questo è un problema del framework utilizzato (fluent UI), so che è una feature molto richiesta, appena verrà implementata la aggiungerò subito a Gordon

> shortcut selezione: vorrei che con shift + click si possano selezionare tutte le righe da quella selezionata a quella su cui è il cursore

Si può fare

> hide ms app flag: vorrei si potesse selezionare/deselezionare solamente quando il cursore è sopra il flag, al momento anche se è sulla stessa 'direzione' lo attiva/disattiva. Mi capita di cliccare erroneamente sullo spazio bianco e vorrei evitare un update senza motivo delle app.

Pure questo, posso fare un check!

**Comment by Stefano-Papa-EOS** [comment]
ok intanto grazie.
Per l'accorpamento delle funzioni mi sarebbe comodo il forceSynch + install

**Comment by Stefano-Papa-EOS** [comment]
ti segnalo qualche problema:
- funzione di shift + click: al primo utilizzo sembra funzionare ma da quelli successivi il sistema mi ritorna il seguente errore

Non-negative number required. (Parameter 'count')
   at System.Collections.Generic.List`1.GetRange(Int32 index, Int32 count)
   at BlazorGenerator.Components.DataGrid.ListDataGrid`1.HandleSingleRecSelection(T Rec)
   at BlazorGenerator.Components.DataGrid.ListDataGrid`1.<BuildRenderTree>b__106_2(FluentDataGridCell`1 cell)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.FluentUI.AspNetCore.Components.FluentDataGridCell`1.HandleOnCellClickAsync() in /_/src/Core/Components/DataGrid/FluentDataGridCell.razor.cs:line 73
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)


![image](https://github.com/user-attachments/assets/3dcff251-fc5b-4f88-9fa9-8e68cf4eeec9)

- Il dimensionamento della finestra non funziona (non ho ancora riavviato il pc). Ho windows 11. Ti servono altre info?
 
-  L'action accorpata non la vedo, è prevista per le prossime release o hai scartato l'idea?



Gordon: 1.1.35.0


riapro l'issue

**Comment by Stefano-Primo-EOS** [comment]
> L'action accorpata non la vedo, è prevista per le prossime release o hai scartato l'idea?

stiamo valutando se/come farla. 
per questa apro una nuova issue

**Comment by Stefano-Papa-EOS** [comment]
ti segnalo altri problemi sul shift + click di selezione (il resto punti è a posto):

1) dopo aver selezionato le righe con shift + click ho usato l'action 'unpublish' e il sistema mi ritorna errore

![image](https://github.com/user-attachments/assets/0de00705-e39a-456f-b73e-0553530990c9)


![image](https://github.com/user-attachments/assets/282ec966-28e2-4d01-bb1a-d95bb696768b)


Sembra che il sistema faccia 'unpublish' solo della prima versione selezionata e non delle altre. 





2) ti segnalo anche un altra piccolezza, sembra che lo shift + click vada solo 'dall'alto verso il basso' e non viceversa come mostro nell'immagine. Qui siamo proprio ai dettagli valuta tu se perderci altro tempo, per me è ok anche così


![image](https://github.com/user-attachments/assets/b1d981fc-308e-4be3-9e21-8c68a7bc273e)

**Comment by Stefano-Primo-EOS** [comment]
Non riesco a riprodurre il tuo errore dell'unpublish

**Comment by Stefano-Papa-EOS** [comment]
ho fatto una registrazione schermo, se non è sufficiente sentiamoci


https://github.com/user-attachments/assets/a9dead77-764b-45fc-8c5d-14fb78d07401

**Comment by Stefano-Primo-EOS** [comment]
ora dovrebbe andare!
