### ISSUE TITLE
Fix: [Autotranslate not work] in [Gordon Xliff Editor]

### ISSUE THREAD

**Issue by Stefano-Schena-EOS** [EOS-Solutions/Gordon#148]
With the same configuration (Providers) of Old Xliff Editor autotranslate function doesn't work

**Comment by Thomas-Torggler-EOS** [comment]
The problem in your case was not the auto-translate, but because of a different bug the project was not loaded correctly (it loaded the base language twice). Any further actions then didn't really work because of the duplicate base.

This problem has been resolved in 3.0.42.
