### ISSUE TITLE
Fix: Update error

### ISSUE THREAD

**Issue by MatteoBuriola** [EOS-Solutions/Gordon#150]
# 🐛 Bug Report
When i open Gordon installer i get the message that a new version is available, i click yes to download the update but it does nothing.

When i try to update Gordon to a new version i get this error:
![image](https://github.com/user-attachments/assets/e594c973-713f-4dc6-b3e3-b759de8662a0)

I get the same error if i try to unistall Gordon.

## Product
- [ ] Gordon (Version: 1.1.32.0)
- [ ] EOS Gordon Installer (Version 0.0.114.0)

**Comment by Thomas-Torggler-EOS** [comment]
Please make sure to use the latest version of EOS Gordon Installer (at least 0.0.116).
If the automatic update of EOS Gordon Installer should also not work, try to update manually by downloading the new version from [https://eos-solutions.github.io/Gordon](https://eos-solutions.github.io/Gordon)

**Comment by MatteoBuriola** [comment]
Downloading the new version of the installer has solved both problem, thanks.
