### ISSUE TITLE
Fix: Docker container list empty

### ISSUE THREAD

**Issue by MatteoBuriola** [EOS-Solutions/Gordon#151]
# 🐛 Bug Report

In Gordon the docker contaner list is empty and when i click the refresh button i get the following message:
![image](https://github.com/user-attachments/assets/aeae887d-9beb-4986-8cdd-e45862594243)

I already lauch Gordon as administrator and i have a container running.

## Product
- Gordon (Version: 1.1.35.0)

**Comment by Stefano-Primo-EOS** [comment]
can you post here the result of the Powershell command: 
`docker ps -a`

**Comment by MatteoBuriola** [comment]
![image](https://github.com/user-attachments/assets/8daa02b2-bd15-4cdb-9aed-c0d0395b1453)


PS C:\Windows\system32> docker ps -a
CONTAINER ID   IMAGE                                        COMMAND                  CREATED        STATUS                            PORTS                                                          NAMES
78ac61c4ef85   mcr.microsoft.com/businesscentral:ltsc2022   "powershell -Commandâ€¦"   16 hours ago   Up 16 hours (unhealthy)           80/tcp, 443/tcp, 1433/tcp, 7045-7049/tcp, 7083/tcp, 8080/tcp   BC
29c282516cbc   9dd46a1ac62d                                 "powershell -Commandâ€¦"   5 weeks ago    Up 8 days (unhealthy)             80/tcp, 443/tcp, 1433/tcp, 7045-7049/tcp, 7083/tcp, 8080/tcp   BC23-5
5de745e023d8   9dd46a1ac62d                                 "powershell -Commandâ€¦"   6 weeks ago    Exited (3221225786) 5 weeks ago                                                                  test

**Comment by Stefano-Primo-EOS** [comment]
Yes, You have containers, but they are unhealthy (are they working?). 
Gordon will filter out this unhealthy containers (just because it means that they are not working correctly)

**Comment by MatteoBuriola** [comment]
I don't know why they are marked as unhealty or how to fix them.

**Comment by Stefano-Primo-EOS** [comment]
Have you updated to Win 11 24H2? 
If so, you need to clean out all docker images and then create container with hyper-v

**Comment by MatteoBuriola** [comment]
Not yet, current Windows version is 23H2, build 22631.4317

**Comment by Stefano-Primo-EOS** [comment]
I will close this issue as it is not related to gordon. 
Try asking ITs to fix your docker problem.
If, after having healthy running containers, the error persists, please open a new one
