### ISSUE TITLE
[Gordon VSCode] feat: add "Build and deploy to server with forcesync"

### ISSUE THREAD

**Issue by Luca-Maritano-EOS** [EOS-Solutions/Gordon#155]
# 🙋 Feature Request

Would be nice to have the command "Build and deploy to server with forcesync" inside VSCode
The main purpose is to mimic the standard functionality present in schemaUpdateMode

## 💁 Possible Solution

Use schemaUpdateMode in app.json

## Product
Name: Gordon
Id: eos-solutions.gordon
Version: 0.1.58

**Comment by Thomas-Torggler-EOS** [comment]
The app synchronization mode will now be selected according to the `schemaUpdateMode` that you have specified in your `launch.config` file. The values are currently mapped as follows (only recreate is not fully supported yet).

`Synchronize` => `Add`
`ForceSync` => `Force`
`Recreate` => `Force`

The used mode will be output to the log window like so:
![image](https://github.com/user-attachments/assets/f752ac64-044e-46e1-a8ce-bef0189f2479)

Will be available in 0.1.60+
