### ISSUE TITLE
feat: Gordon VScode: Add option to download symbol

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#157]
# 🙋 Feature Request
Add an option to clear the .packages folder before downloading symbols.
It is a useful option to always have the exact version present in the DB from where the symbols are downloaded

## 🤔 Expected Behavior
Delete all file in .packages folder and download symbol

## 😯 Current Behavior
Download the symbols in .packages folder and I have multiple version to same app in this folder.

## Product
- [X] Gordon VsCode (Version: 0.1.58)

**Comment by Thomas-Torggler-EOS** [comment]
Available in 0.1.64
