### ISSUE TITLE
[Gordon VSCode] Update dependency shows an empty list without further explanation when no dependencies are found

### ISSUE THREAD

**Issue by Luca-Maritano-EOS** [EOS-Solutions/Gordon#160]
# 🐛 Bug Report

Using the function Update dependency on "Server" --> "Dependencies" --> right click shows an empty list when no dependencies are found, without a clear explanation to the user.

## 💻 Repro

1. Select a dependency
2. Forget to assign a feed
3. Right click
4. Update dependency --> An empty list in the top bar is shown

## 🤔 Expected Behavior

A message in the console saying "No updates found"

## 📸 Screenshots
  
![image](https://github.com/user-attachments/assets/e14133ec-f377-4a1c-aa20-c026a91e3632)
![image](https://github.com/user-attachments/assets/03e7b15e-da56-417f-8b18-bb609616e9f2)

## Product
Gordon VSCode
Version: 0.1.61

**Comment by Thomas-Torggler-EOS** [comment]
Available in 0.1.64
