### ISSUE TITLE
Fix: starting container in Gordon issue

### ISSUE THREAD

**Issue by Daniele-Corona-EOS** [EOS-Solutions/Gordon#161]
# 🐛 Bug Report
If I select a container and press the start command Gordon show this message.

## 💻 Repro
Select a container and press start container. Gordon show the message "You need to select container!" without starting.

## 🤔 Expected Behavior
The container must start.

## 😯 Current Behavior
The container does not start

## 📸 Screenshots
![image](https://github.com/user-attachments/assets/3b00ea30-c8b9-42f7-9752-ae7894a80a2f)

## Product
- [x] Gordon (Version: 1.1.39.0)

**Comment by Stefano-Primo-EOS** [comment]
Fixed with 1.1.40
