### ISSUE TITLE
Fix: Docker container list empty

### ISSUE THREAD

**Issue by MatteoBuriola** [EOS-Solutions/Gordon#164]
In Gordon the docker contaner list is empty and when i click the refresh button i get the following message:
![image](https://github.com/user-attachments/assets/eee23d9b-2d00-4180-94aa-ce550c9bbc49)

I already lauch Gordon as administrator and i have a container running.
The container status is healty.
![image](https://github.com/user-attachments/assets/ec9e0a4b-b88e-4c99-8e2e-500aa25b16bb)

Product
Gordon (Version: 1.1.42.0)

Windows version 23H2, build 22631.4317

**Comment by Stefano-Primo-EOS** [comment]
Could you post also a screen of your User Settings?

**Comment by MatteoBuriola** [comment]
![image](https://github.com/user-attachments/assets/91f66e66-2b4b-41b7-8fc1-fb7894b93c45)

I downloaded the new licence yesterday.

**Comment by Stefano-Primo-EOS** [comment]
Please, remove the localhost as Docker_Host and try again

**Comment by MatteoBuriola** [comment]
Now it works, thanks.
