### ISSUE TITLE
feat: add Confirmation dialog at Reload button in Gordon Xliff Editor

### ISSUE THREAD

**Issue by Paolo-Visenti-EOS** [EOS-Solutions/Gordon#167]
# 🙋 if possible, a new confirmation dialog at Reload button. It's too close to SAVE button

![image](https://github.com/user-attachments/assets/8c3652dd-c92a-4773-beb0-7b36fe3013d5)

Thanks a lot

Gordon Xliff Editor Version 3.0.45.0

**Comment by Thomas-Torggler-EOS** [comment]
It will now ask for confirmation when trying to refresh and there are unsaved changes.

Available in 3.0.46.
