### ISSUE TITLE
Fix: glitch selezione app

### ISSUE THREAD

**Issue by Stefano-Papa-EOS** [EOS-Solutions/Gordon#168]
# 🐛 Bug Report

glitch grafico alla selezione delle app

## 💻 Repro

Quando seleziono delle righe ne vengono selezionate o deselezionate altre in modo anomalo.
Sto operando da una lista di app che risultano con aggiornamento disponibile dal feed bc25. Non mi è mai successo in altre situazioni. 
Nello specifico ho utilizzato il flag di seleziona tutto in altro a sinistra e successivamente sto deselezionando quelle che non mi interessano. Non sto utilizzando shortcut.
Vedi video per i dettagli.

## 📸 Screenshots

https://github.com/user-attachments/assets/262c178c-13da-480f-9ab5-897296c759e8

## Product
- [ ] Gordon (Version: 1.1.42.0)

**Comment by Stefano-Primo-EOS** [comment]
Will be available in Weekly Release W47
