### ISSUE TITLE
Fix: properly handle en-us files when present (xliff editor)

### ISSUE THREAD

**Issue by Beatrice-Foffani-EOS** [EOS-Solutions/Gordon#170]
# 🐛 Bug Report

When a specific en-us file is present in the translation folder other than the g.xlf file, XLIFF editor fails to interpret it resulting in a broken application (object types and names are missing, and any new entry in the .g.xlf file that is not also present in the en-us one is missing).

## 💻 Repro

Create translation files for en-us. Add a new label or caption anywhere in the project. Open XLIFF editor and click on filter missing

## 🤔 Expected Behavior

I should be able to see the new label or caption available for translation

## 😯 Current Behavior

The label is missing, plus other parts of the applications are broken (e.g. object types, names and properties)

## 📸 Screenshots

![image](https://github.com/user-attachments/assets/b5d0aa99-875b-4493-80fc-8fa3c0a6f46c)

## Product
Gordon Xliff Editor 3.0.46.0

**Comment by Thomas-Torggler-EOS** [comment]
Any translation file for en-US will now be ignored in XLIFF Editor (except the base file of course). Translating `en-US` (as base) to `en-US` (as non-base) makes no sense: BC translation XLIFF files have a `source` and a `target` property. BC will only translate if the text in `source` is matching the one from the `.g.xlf` file. But with both being `en-US` you'd basically have two different captions for `en-US`.

Will be available in W47 milestone.
