### ISSUE TITLE
Utilizzo Function API per file Mgt BC Cloud

### ISSUE THREAD

**Issue by MatteoColombi96** [EOS-Solutions/Gordon#172]
Buongiorno,
sto tentando di effettuare una configurazione per gestione di file attraverso l’utilizzo API EOS però ricevo l’errore HTTP401 quando eseguo una funzione del wrapper che si poggia sulla configurazione EAL.

Lato configurazione API ho impostato il seguente:

![impostazione api](https://github.com/user-attachments/assets/343cc4f9-626c-4453-b3a6-3c7f04b2044c)

Lato Business central, poggiandomi sulla pagina di test fornita dal vostro github stavo provando a effettuare una letture di file (premetto che son consapevole che il path1 = test mi darebbe errore, però il sistema si ferma prima secondo me con quell’errore HTTP401).

![pagina test funzioni](https://github.com/user-attachments/assets/cf4a4b9e-b035-43e7-a5c5-f755c3ff5e8c)

La configurazione del servizio EAL è questo, la chiave API ho incollato correttamente quella presa dalla prima immagine:
![configurazione servizio eal](https://github.com/user-attachments/assets/da425b8f-096b-4341-a545-c7faa3c5c798)

Utilizzo già sullo stesso servizio l’API per la gestione dei barcode e questa non mi da problemi, vorrei sapere cosa sto sbagliando.

Grazie,

**Comment by Stefano-Primo-EOS** [comment]
risponde 401 perchè non si è autorizzati. 
Ma questo caso suppongo sia per la configurazione fatta. 
Per motivi di sicurezza, abbiamo deciso di non abilitare la FunctionAPI nel leggere direttamente sotto C:\ (perchè si potrebbero fare operazioni distruttive per il sistema operativo). 

Mettendo un'altra cartella come "Root Folder" (ad esempio c:\FunctionApiFiles) risponde correttamente?

**Comment by Stefano-Primo-EOS** [comment]
Usando la FunctionAPI da swagger (localhost:9977 --> swagger) funziona? 

Io userei come metodo il "GetFiles" che dovrebbe restituire una lista di file! 

Per lo share dire rete, quello potrebbe comunque essere un problema di permessi (la functionAPI è un servizio di windows, l'utente che esegue il servizio deve anche avere gli accessi alla cartella)

Ultimo punto: La FunctionAPI è stata installata con scope User-Wide o Machine-Wide? Se fosse User-Wide, sarebbe meglio installarla nell'altro modo!

**Comment by MatteoColombi96** [comment]
Ciao Stefano,
reinstallando la function API con scope USER-MACHINE (Non lo avevo fatto con questo scope nei test precedenti) e ripetendo i test confermo di essere riuscito a lanciare alcune funzioni come ReadFile | GetFiles.

Grazie,
Matteo
