### ISSUE TITLE
feat: add Shortcut keys in Gordon

### ISSUE THREAD

**Issue by Andrea-Antolini-EOS** [EOS-Solutions/Gordon#174]
# 🙋 Feature Request

It could be useful if in Gordon VSCode extension (and possibly in Gordon APP) some of the commands could be triggered using  keyboard shortcuts., without the need (for VSCode) to map some user-defined ones.

the most wanted shortcuts could be: build&deploy to server, focus on gordon view, import license

## Products

- [ ]  Gordon VSCode
- [ ]  Gordon WebApp

**Comment by Thomas-Torggler-EOS** [comment]
Available in 0.1.66
