### ISSUE TITLE
Fix: Auto-translate "Selected" in Gordon Xliff Editor

### ISSUE THREAD

**Issue by Mariangela-DeMaio-EOS** [EOS-Solutions/Gordon#175]
# 🐛 Bug Report

Hi,
i found an issue in Gordon Xliff Editor:
by selecting just one line to translate and using Auto-Translate Apply to "Selected", the app translates all missing lines.

## 📸 Screenshots

![image](https://github.com/user-attachments/assets/953349f5-6ffd-4dff-ab67-22f7e39b2e52)

![image](https://github.com/user-attachments/assets/4fe4c9e5-b155-473c-9a16-757ccc113366)

![image](https://github.com/user-attachments/assets/3a800695-a1ed-4c04-9422-e91669836e02)

## Product

- [ ] Gordon Xliff Editor Version: 3.0.46.0

**Comment by Thomas-Torggler-EOS** [comment]
Fixed. Will become available with Milestone **w48**
