### ISSUE TITLE
Fix: Gordon - Rimettere azione "installa project dependencies"

### ISSUE THREAD

**Issue by Delpixe** [EOS-Solutions/Gordon#176]
# 🐛 Bug Report

## 🤔 Expected Behavior

dandogli l'app.json in pasto, che vengano installate tutte le app del feed selezionato

## 😯 Current Behavior

se provo ad utilizzare install app from file mi esce questo errore, quando gli dò in pasto l'app.json
![image](https://github.com/user-attachments/assets/b58299f6-5843-4099-8996-71439874abe6)

## 💁 Possible Solution

nella vecchia versione c'era e funzionava!

## 📸 Screenshots
![image](https://github.com/user-attachments/assets/dba8e52e-a60e-4c3f-8a87-fd2962cd8397)

## Product
- [x] Gordon (Version: 1.1.43)

**Comment by Stefano-Primo-EOS** [comment]
Stavo valutando questa issue, usando gordon per vscode sarebbe già disponibile questa funzionalità.

**Comment by Delpixe** [comment]
Comeeee?On 19 Nov 2024, at 14:41, Stefano Primo ***@***.***> wrote:﻿
Stavo valutando questa issue, usando gordon per vscode sarebbe già disponibile questa funzionalità.

**Comment by Stefano-Primo-EOS** [comment]
https://docs.eos-solutions.it/en/docs/apps-func/vscode-introduction/vscode-package-management.html#restore-dependencies
