### ISSUE TITLE
Fix: apps update in EOS Gordon Installer

### ISSUE THREAD

**Issue by Diaci04** [EOS-Solutions/Gordon#179]
# 🐛 Bug Report
Trying to update Gordon and Gordon XLIFF from Gordon Installer, I got the following error "failed to download deployer"
[gordon-installer.log](https://github.com/user-attachments/files/17812421/gordon-installer.log)

## 📸 Screenshots
![Immagine 2024-11-19 100319](https://github.com/user-attachments/assets/fdd25ac0-68f6-4964-97a7-7bd869c97ea9)

## Product
- [ ] EOS Gordon Installer

**Comment by Stefano-Primo-EOS** [comment]
There was a problem with the Gordon Installer, please update to the latest version via the official downloader: 
https://eos-solutions.github.io/Gordon/

**Comment by Diaci04** [comment]
Thanks, I confirm that version 116 works.
