### ISSUE TITLE
Gordon VsCode: Error if EnvironmentType not present in launch.json

### ISSUE THREAD

**Issue by Stefano-Primo-EOS** [EOS-Solutions/Gordon#181]
# 🐛 Bug Report
If prop environmentType is not present in launch.json an error will show up and gordon will not work.

TypeError: Cannot read properties of undefined (reading 'toString')
    at new d (c:\Users\user\.vscode\extensions\eos-solutions.gordon-0.1.66\dist\extension.js:1:29961)
    at c:\Users\user\.vscode\extensions\eos-solutions.gordon-0.1.66\dist\extension.js:1:14687
    at Array.forEach (<anonymous>)
    at c.getChildren (c:\Users\user\.vscode\extensions\eos-solutions.gordon-0.1.66\dist\extension.js:1:14667)

## 🤔 Expected Behavior

Defaults to OnPrem if not present

## Product
- [ ] Gordon (Version: _WriteHereTheVersion_)
- [ ] Gordon Powershell (Version: _WriteHereTheVersion_)
- [ ] Gordon Service (Version: _WriteHereTheVersion_)
- [ ] Gordon Xliff Editor
- [ ] EOS Gordon Installer

**Comment by Thomas-Torggler-EOS** [comment]
Resolved in 0.1.68
