### ISSUE TITLE
Fix: Folder Feeds don't work anymore after updating to version 1.1.43.0

### ISSUE THREAD

**Issue by FabioC34** [EOS-Solutions/Gordon#184]
# 🐛 Bug Report

After updating to version 1.1.43.0 of Gordon, Folder Feeds don't work anymore for updates.
Selecting the feed with Show = Update Available the list is empty.
If I select Show = Feed Apps many columns are empty, maybe for this reason Update is not possible

## 💻 Repro

Select a folder feed with one or more app files

## 🤔 Expected Behavior

The update should be possible (if app version is greater than the installed one)

## 📸 Screenshots
![image](https://github.com/user-attachments/assets/78fdd814-031e-44e5-80fe-ffeb9836190a)

![image](https://github.com/user-attachments/assets/55625ac6-b9c0-4506-a2c9-d717d6920eec)

## Product
- Gordon 1.1.43.0

**Comment by Stefano-Primo-EOS** [comment]
from what i see, the apps are already installed in the service, so you want't see nothing for update, am I right?

**Comment by FabioC34** [comment]
Yes, the apps are already installed, but I have in Folder Feed a new version of the app, but I can’t see it and can’t update it (until version 1.1.42.0 I was able to do it, I did it several time a day)

Fabio

Da: Stefano Primo ***@***.***>
Inviato: venerdì 22 novembre 2024 12:59
A: EOS-Solutions/Gordon ***@***.***>
Cc: Fabio Cipriani ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/Gordon] Fix: Folder Feeds don't work anymore after updating to version 1.1.43.0 (Issue #184)


from what i see, the apps are already installed in the service, so you want't see nothing for update, am I right?

—
Reply to this email directly, view it on GitHub<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FGordon%2Fissues%2F184%23issuecomment-2493592506&e=d4e01e8e&h=21ff590d&f=n&p=y>, or unsubscribe<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANW6LO4PQUOXLCSSGI7BRJ32B4MBXAVCNFSM6AAAAABSJGBQ2KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOJTGU4TENJQGY&e=d4e01e8e&h=19335509&f=n&p=y>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

--
Questo messaggio e' stato analizzato con Libraesva ESG ed e' risultato non infetto.
Segnala come spam.<https://mx2.univergomma.it/action/4Xvttj1XVjzH/report-as-bad>
Mettilo in blocklist.<https://mx2.univergomma.it/action/4Xvttj1XVjzH/blocklist>

**Comment by Stefano-Primo-EOS** [comment]
Could you please post here: 
The apps in the Folder
The apps in Service and in the Feed.

**Comment by FabioC34** [comment]
These are the apps in Service:
![image](https://github.com/user-attachments/assets/e60af88b-b644-492d-b472-3c09ab587bff)

These are the apps in Folder (the one highlighted has a newer version, .3795 instead of .3794):
![image](https://github.com/user-attachments/assets/01ff1cdc-54dd-4d32-a520-8af4c0806272)

Update available is empty:
![image](https://github.com/user-attachments/assets/8e257be8-e804-4dd2-820c-8314793c15a0)

And Feed Apps does not show version:
![image](https://github.com/user-attachments/assets/d9dff347-6142-4db9-9d08-47cfaf9e1373)

**Comment by Stefano-Primo-EOS** [comment]
I've reproduced the error, I will investigate
