### ISSUE TITLE
feat: add "Open Recent" in Gordon XLIFF

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#186]
# 🙋 Feature Request
As available in many editing programs, is it possible to have a list of the last N folders opened? Useful if you work on multiple apps/projects at the same time

## 💻 Examples
![image](https://github.com/user-attachments/assets/e9485943-8ad7-413d-b6c7-55721a656b6b)

## Product
- [X] Gordon Xliff Editor

**Comment by Stefano-Primo-EOS** [comment]
have you tried to add a default program for opening the .xliffconfig files? 
 
![image](https://github.com/user-attachments/assets/1faa8c08-50ae-4260-92dc-29f8d5a3ad21)


with so, you can open the Xliff Editor directly from a project. (and also from vscode with "Open Externally"

![image](https://github.com/user-attachments/assets/f1b7f177-24ac-4d8d-8a41-6d0f5964f136)

**Comment by alessiopellindgm** [comment]
Yes, I have used this method, but it opens only one folder at a time and, if the program is already open, it does not open any folders either from VsCode or by opening the xliffconfig file from the folder

Using "Open Folder" of XLIFF Editor I can open multiple tabs, one per folder.
