### ISSUE TITLE
Info Tecnica per gestione files con EOS Function API di Gordon

### ISSUE THREAD

**Issue by MatteoColombi96** [EOS-Solutions/Gordon#187]
Buongiorno,
volevo chiedere un info tecnica riguardante la gestione dei files tramite l'utilizzo della Function API di Gordon.  
Volevo sapere se è possibile gestire files su radici diverse, ad esempio voglio spostare un file dal percorso **C:\**temp\test.txt in **S:\**temp\.
Navigando gli esempi non ho trovato una risoluzione per un problema del genere, per caso non è possibile farlo? I files per poter essere gestiti devono rimanere sotto la stessa cartella di Root specificata nella configurazione API File System?

Grazie,
Matteo

**Comment by Stefano-Primo-EOS** [comment]
con la stessa API Key no, in quanto i file devono rimanere all'interno della stessa Root. 
Però si può gestire usando due API Key. 
Per spostare i file sarebbe una operazione: Download + Upload + Delete

**Comment by MatteoColombi96** [comment]
Ok grazie chiaro.

Buona giornata.
