### ISSUE TITLE
Fix: Gordon Build in Gordon VsCode

### ISSUE THREAD

**Issue by Stefano-Primo-EOS** [EOS-Solutions/Gordon#189]
# 🐛 Bug Report
If empty settings.json, gordon build will result in this error:
```
Error reading JObject from JsonReader. Path '', line 0, position 0.
[fail] Error reading JObject from JsonReader. Path '', line 0, position 0.
```

## 💻 Repro

1. Create an empty settings.json file in .vscode folder
2. gordon build
3. error

## 💁 Possible Solution
check content length before parse

## Product
- [ ] Gordon (Version: _WriteHereTheVersion_)
- [x] Gordon VSCode (Version: 0.1.69)
- [ ] Gordon Powershell (Version: _WriteHereTheVersion_)
- [ ] Gordon Service (Version: _WriteHereTheVersion_)
- [ ] Gordon Xliff Editor
- [ ] EOS Gordon Installer

**Comment by Thomas-Torggler-EOS** [comment]
Available in 0.1.73
