### ISSUE TITLE
feat: add options in Gordon VSCode build configuration

### ISSUE THREAD

**Issue by Andrea-Antolini-EOS** [EOS-Solutions/Gordon#190]
# 🙋 Feature Request
It would be extremely useful if in Gordon VSCode we could add the following options that are present in install command (Gordon WebApp):

![Screenshot 2024-12-06 144317](https://github.com/user-attachments/assets/d157a639-497e-4c36-87f5-4c5ececcf632)

## 🤔 Expected Behavior

in the build configuration json files we can add the following options

`"Options":{ 
"SkipVerification": true, "SynchronizationMode": "Add", "DependenciesSynchronizationMode": "Add"
}`

## Product
- [x] Gordon VSCode

**Comment by Thomas-Torggler-EOS** [comment]
Use `schemaUpdateMode` in launch.json for this. See #155
