### ISSUE TITLE
Fix: [HttpClient.Timeout error] in [Gordon when access to a specific service]

### ISSUE THREAD

**Issue by Giuliano-Velludo-EOS** [EOS-Solutions/Gordon#191]
Ciao premetto che non sò se sia un bug:
Cerco di accedere al server br-bcdev2.eos.it e service EOSPOWERAPPS
e mi restituisce l'errore;
![image](https://github.com/user-attachments/assets/dfa40c05-8c1e-4e39-be34-1d46456e9c79)

Sono in sede a Treviso.
Altri servizi su quel server rispondono
Forse dipende dal fatto che è lento ?

Grazie

## Product
- [ ] Gordon (Version: _1.1.45.0_)

**Comment by Thomas-Torggler-EOS** [comment]
Se gli altri servizi rispondono, allora direi no, non è un bug di Gordon, ma un problema del servizio.
Ho provato oggi dopo un riavvio ma cmq. non risponde.
Ho scoperto che su questo server gira una versione vecchia di Gordon Service (2.0.25). Non so se il problema è collegato, ma farei aggiornare all'ultima disponibile.

**Comment by Giuliano-Velludo-EOS** [comment]
Ciao ho fatto aggiornare il servizio sul server e ora funziona correttamente. Grazie
