### ISSUE TITLE
BC25.2 installing app from gordon

### ISSUE THREAD

**Issue by Fabrizio-Rovatti-EOS** [EOS-Solutions/Gordon#196]
Quando installi una qualsiasi app ne installa una poi restitusce questo errore
17/12/2024 16:45:47 - Exception has been thrown by the target of an invocation.

## Product
- [ ] Gordon (Version: _WriteHereTheVersion_)
- [ ] Gordon VSCode (Version: _WriteHereTheVersion_)
- [ ] Gordon Powershell (Version: _WriteHereTheVersion_)
- [ ] Gordon Service (Version: _WriteHereTheVersion_)
- [ ] Gordon Xliff Editor
- [ ] EOS Gordon Installer

**Comment by Thomas-Torggler-EOS** [comment]
Questo è un problema dato da modifiche alla piattaforma BC da BC25.2+ incluso certe versioni di BC25.1 (solo sandbox) e le preview di BC26. Lo abbiamo risolto ed il fix è disponibile su GordonService 3.0.23+.
