### ISSUE TITLE
Active sessions should give UI feedback for "Kill session"

### ISSUE THREAD

**Issue by Thomas-Torggler-EOS** [EOS-Solutions/Gordon#22]
**Is your feature request related to a problem? Please describe.**
The list of "active sessions" doesn't give feed back if "Kill Session" was successful.

**Describe the solution you'd like**
Killing a session should give feed back if it failed (or not).

**Describe alternatives you've considered**
None.

**Product**
- [1.0.104 ] Gordon WebApp

**Comment by Stefano-Primo-EOS** [comment]
Done, 1.0.105
