### ISSUE TITLE
Table view column size is buggy

### ISSUE THREAD

**Issue by Thomas-Torggler-EOS** [EOS-Solutions/Gordon#23]
**Describe the bug**
When resizing a column in the table view (list of apps), the other columns are resized strangely:
![image](https://github.com/EOS-Solutions/Gordon/assets/163338087/730b101d-8a20-4ab8-b163-583a6d3c7984)

**To Reproduce**
1. Go to app
2. Resize any column

**Product**
- [ ] Gordon WebApp (Version: 1.0.104)

**Comment by Stefano-Primo-EOS** [comment]
fix in 1.0.106
