### ISSUE TITLE
Log seems to be useless, reporting too little, move to persistent file log

### ISSUE THREAD

**Issue by Thomas-Torggler-EOS** [EOS-Solutions/Gordon#26]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The log button should open a log that was written to a file instead of displaying it in-app. Also, the core should write to that file log instead of the in-app. This for usability.

**Describe alternatives you've considered**
None.

**Product**
- [1.0.121 ] Gordon WebApp
- [ /] Gordon Powershell
- [ 3.0.11] Bare.WebApi

**Comment by Stefano-Primo-EOS** [comment]
Log now richer, next step is to write into a file
