### ISSUE TITLE
Add colors for Container App List

### ISSUE THREAD

**Issue by Fabio-Vitalba-EOS** [EOS-Solutions/Gordon#45]
**Is your feature request related to a problem? Please describe.**
In Smeagol it was quick to see whether an App needed Installation, Update or Nothing. It would be nice to have a similar highlighting in Gordon.

**Describe the solution you'd like**
I'd like to have icons in the List of Apps of a Container that show whether an App is:
* Installed, 
* Requires Updating, 
* Is Unpublished, or 
* Can be installed.

However, any visual help would be nice.

**Describe alternatives you've considered**
Alternative solutions could be to simply color each line of the App differently based on its Installation Status.

**Product**
- [x] Gordon WebApp
- [ ] Gordon Powershell
- [ ] Bare.WebApi

**Additional context**
None

**Comment by f4n0** [comment]
For unpublished apps, the row color is different from the others. 
For the apps "To Install" and "To Update" there are specific tabs
