### ISSUE TITLE
Shortcut generali

### ISSUE THREAD

**Issue by Stefano-Papa-EOS** [EOS-Solutions/Gordon#53]
Suggerisco alcuni shortcut da inserire per migliorare l'esperienza utente:
- ctrl + f oppure f3 per posizionarsi sulla lente di ricerca delle app
- shift + click per la selezione multipla delle app (quando ne si vogliono selezionare solo una parte)
- alt + freccia indietro per tornare alla schermata precedente

**Comment by Stefano-Primo-EOS** [comment]
Nell'ultima versione sono stati aggiunti `f3` e `alt + ←`

il shift+click bisogna aspettare una implmenentazione dal framework (in arrivo nella prossima release)

**Comment by Stefano-Papa-EOS** [comment]
Ciao, riporto un bug relativo allo shortcut F3 di ricerca, in diversi casi il sistema crasha quando lo utilizzo.
Nello specifico crasha sempre dalla lista dei server, invece dalla lista home solo alla seconda iterazione (per intenderci appena aperta l'app non da problemi). Tramite cursore la ricerca funziona correttamente.
Non ho altri dettagli per comprendere il problema, rimango a disposizione per casi d'uso.
Ho aggiornato all'ultima versione stamattina 1.0.143
