### ISSUE TITLE
Save FeedName in container page

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#58]
**Is your feature request related to a problem? Please describe.**
On the "Apps" page, the "FeedName" field doesn't remain saved and must be selected every time open this page.
![image](https://github.com/EOS-Solutions/Gordon/assets/97117499/c8b421fb-2464-420f-96c8-5da397dc9d71)

**Describe the solution you'd like**
Have a setup where you can choose the default feed for each container (as happened in Smeagol)

**Product**
- [X] Gordon WebApp
- [ ] Gordon Powershell
- [ ] Bare.WebApi

**Comment by f4n0** [comment]
This feature already exists, on container/service list you can choose the action "Select Feeds"

**Comment by alessiopellindgm** [comment]
Okay. I await the solution to an issue already reported
https://github.com/EOS-Solutions/Gordon/issues/57
