### ISSUE TITLE
Error during restore dependencies from Gordon Extension

### ISSUE THREAD

**Issue by Davide-Allasia-EOS** [EOS-Solutions/Gordon#60]
By executing the function:

Visual Studio Code
Extension Gordon v0.1.27
->Project Dependencies (right click)
--> Restore Dependencies

The following error is returned
The folder '<Projcet_Folder>\OCE.BC' does not appear to be a valid AL project.

Thanks

[done]
![Gordon_20240604](https://github.com/EOS-Solutions/Gordon/assets/163286740/64ab18bd-7012-4ae0-a768-8ded00a97d6b)

**Comment by Thomas-Torggler-EOS** [comment]
Resolved in 0.1.31
