### ISSUE TITLE
Scope in App List

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#66]
**Is your feature request related to a problem? Please describe.**
In Smeagol c'è la colonna "Scope" che è molto utile per capire, a colpo d'occhio, se l'app è stata installata da Gordon o direttamente da VSCode capire come installare l'app.
![image](https://github.com/EOS-Solutions/Gordon/assets/97117499/d7b6ec28-8ad2-459b-8e39-0343b4e058ec)

**Product**
- [X] Gordon WebApp
- [ ] Gordon Powershell
- [ ] Bare.WebApi

**Comment by Stefano-Primo-EOS** [comment]
Disponibile nella prossima versione
