### ISSUE TITLE
Restart service container

### ISSUE THREAD

**Issue by Paolo-Visenti-EOS** [EOS-Solutions/Gordon#68]
Restarting the service container causes the application to close

![image](https://github.com/EOS-Solutions/Gordon/assets/114222208/0fff783c-40dd-40ed-b437-47a1197250a4)

Everything is up to date

**Comment by Stefano-Primo-EOS** [comment]
You are not using BARE, see this repo: 
https://github.com/EOS-Solutions/Scripts/tree/master/BARE
