### ISSUE TITLE
Drop area for "Install from file" does not work

### ISSUE THREAD

**Issue by Thomas-Torggler-EOS** [EOS-Solutions/Gordon#71]
**Describe the bug**
When using drag&drop to install an app from a file, the drop area does not seem to work. Windows does strange things, looks for an app (see screenshot below)

**To Reproduce**
1. Go to app manager
2. Click on "Install from File"
3. Drag&drop a file to the drop area

**Screenshots**
![image](https://github.com/EOS-Solutions/Gordon/assets/163338087/91235d04-190c-4cbf-957f-c35f007e2df8)

**Product**
- [x] Gordon WebApp (Version: 1.0.148)
- [ ] Gordon Powershell (Version: _WriteHereTheVersion_)
- [ ] Bare.WebApi (Version: _WriteHereTheVersion_)

**Comment by f4n0** [comment]
this happens if the file is dropped outside the green dotted box

**Comment by Thomas-Torggler-EOS** [comment]
OK, what I did is drag & drop a file from VS Code directly onto the dropbox. I didn't drop a file from the explorer.

I reckon that the explorer drag-drop-operations gives you a file, while VSCode actually gives you just a string (= path to the file). Would be nice if both are supported.

________________________________
