### ISSUE TITLE
Error "Sequence contains no elements"

### ISSUE THREAD

**Issue by alessiopellindgm** [EOS-Solutions/Gordon#72]
**Describe the bug**
While installing an app.. What causes this error?
![image](https://github.com/EOS-Solutions/Gordon/assets/97117499/55231f0c-7b33-44be-bb3e-6c2e77e1f83e)

```
Getting apps from Service
Retrived metadata from service (8897 ms)
Get app from service finished (0 ms)
Getting apps from Feed
Retrived metadata from feed (1526 ms)
Get app from feed finished (0 ms)
Getting apps from Service
Retrived metadata from service (10162 ms)
Get app from service finished (0 ms)
Getting apps from Feed
Retrived metadata from feed (1848 ms)
Get app from feed finished (0 ms)
Resolving dependencies using policy 'MinimumVersion'
Sequence contains no elements
Getting apps from Service
Retrived metadata from service (8959 ms)
Get app from service finished (0 ms)
Getting apps from Feed
Retrived metadata from feed (2229 ms)
Get app from feed finished (0 ms)
```

**Product**
- [X] Gordon WebApp (Version: 1.0.150.0)
- [ ] Gordon Powershell (Version: _WriteHereTheVersion_)
- [X] Bare.WebApi (Version: 3.0.14)

**Comment by Stefano-Primo-EOS** [comment]
Which feed are you using?

**Comment by alessiopellindgm** [comment]
I am using a feed on a local folder where I insert the apps generated by DevOps or directly from the VSCode.
In this case there were two apps at an updated version (one dependent on the other).

**Comment by Stefano-Primo-EOS** [comment]
After updating to the latest version, could you please send the log under "%appdata%\EOS Solutions\Gordon.WebApp\Errors" ?
