### ISSUE TITLE
glitch colonne quando si ridimensionano + scomparsa f3

### ISSUE THREAD

**Issue by Stefano-Papa-EOS** [EOS-Solutions/Gordon#80]
# 🐛 Bug Report

glitch colonne quando si ridimensionano + scomparsa f3

## 💻 Repro

Quando provo a ridimensionare le colonne dalla lista app di un servizio la colonna di selezione scompare e tutte le altre colonne vengono ridotte, il problema è molto più evidente dopo aver utilizzato la lente ricerca.
Non mi funziona più l'f3 per la ricerca, è sato rimosso?

## 📸 Screenshots
![image](https://github.com/EOS-Solutions/Gordon/assets/163179557/6ac97fd0-d843-4257-a624-0f447a28a3e3)

## Product
- Gordon WebApp (1.0.158.0)

**Comment by Stefano-Primo-EOS** [comment]
l'F3 è stato risolto. 
Il resize delle colonne è un problema che sto cercando di risolvere direttamente nella libreria di MS. 
Chiudo il ticket intanto!
