### ISSUE TITLE
BC24 istances not visible in Gordon - server list

### ISSUE THREAD

**Issue by gianlucadorlandodgm** [EOS-Solutions/Gordon#90]
In a customer server with BC19 on Prem we have installed BC23 and BC24 and tried to migrate DB PROD (BC19) to PRODBC23 and PRODBC24 for our tests.
Migrations competed successfully, we can access PRODBC23 and PRODBC24 through Web Client.
![image](https://github.com/user-attachments/assets/867f7e54-e480-47e2-a7d5-b28fcfdfae29)

Updated Smeagol, disinstalled Smeagol NVT and installed Bare, Gordon, ... all Machine Wide.
![image](https://github.com/user-attachments/assets/3bd9bf86-4d14-4a8b-9009-aacc2f01bf64)

In Gordon, setup of server list:
![image](https://github.com/user-attachments/assets/69c9c81c-794d-48d6-b89d-49d255a350fe)

Instance PRODBC24 is not showing, either in localhost or in server-dbc365-2
![image](https://github.com/user-attachments/assets/8f18469f-fdbd-437d-9565-6573f6caedf1)

Creation of instances PRODBC23 and PRODBC4 was done with similar scripts, only differences are service name and use of Powershell 6/7, both services run with same domain account (not network service), mangement service, management api ports etc are the same for all service instances. 
Alredy tried to restart srv/services, restart from scratch, even other BC24 services created with different names are not shown. 
Accessing and using ProdBC23 through Gordon seems ok, no error, a list of installed apps is showing etc. 

Thanks for support.
 
## Product
- [ ] Gordon WebApp (Version: 1.0.162)
- [ ] Bare.WebApi (Version: 3.0.16)

**Comment by f4n0** [comment]
You cannot have both Nvt Remote and Bare WebApi installed (as they share the same port). Make sure you use Bare (as only this have the capability to handle BC24)

**Comment by gianlucadorlandodgm** [comment]
Has i wrote: "Updated Smeagol, disinstalled Smeagol NVT and installed Bare, Gordon, ... all Machine Wide."
Thanks.
G.

**Comment by Stefano-Primo-EOS** [comment]
Could you please check if the windows service of NVT is really stopped and Bare is running?

**Comment by Stefano-Primo-EOS** [comment]
Could you attach the "Customsetting.config" here? One of the "visible" service and one for PRODBC24. 

In WindowsService could you please attach the "PathToExecutable" of PRODBC24? 

![image](https://github.com/user-attachments/assets/c63388c2-d89e-4629-9f1a-b649331497d0)

**Comment by gianlucadorlandodgm** [comment]
Hi, i've found the bug: 
Following your suggestions i've checked what's the the path to executable of PRODBC24 service, it is:
C:\Program Files\Microsoft Dynamics 365 Business Central\240\Service\Microsoft.Dynamics.Nav.Server.exe $PRODBC24 config "C:\Program Files\Microsoft Dynamics 365 Business Central\240\Service\Instances\PRODBC24\PRODBC24.config"

This is PRODBC23 in services:
"C:\Program Files\Microsoft Dynamics 365 Business Central\230\Service\Microsoft.Dynamics.Nav.Server.exe" $PRODBC23 config "C:\Program Files\Microsoft Dynamics 365 Business Central\230\Service\Instances\PRODBC23\PRODBC23.config"

In PRODBC23 path of exe is sorrounded by " , in PRODBC24 " are missing, so i manually edited it through registry:
"C:\Program Files\Microsoft Dynamics 365 Business Central\240\Service\Microsoft.Dynamics.Nav.Server.exe" $PRODBC24 config "C:\Program Files\Microsoft Dynamics 365 Business Central\240\Service\Instances\PRODBC24\PRODBC24.config"

After this editing a refresh in Gordon is sufficient to show PRODBC24 and manage it.
Could you please fix this so no manually editing is necessary?
Thanks.
G.

**Comment by Thomas-Torggler-EOS** [comment]
This is a bug in the `New-NavServerInstance` cmdlet rather than Gordon and/or Gordon Service (BARE). A path containing spaces *must* be escaped (enclosed) using `"`. This is true for everything in Windows. The fact that - in whatever way - Windows is able to deal with services that have such an invalid path does not change that fact that it is still an invalid path. As such most of the system libraries will not correctly handle this and you will (most probably) run into other problems.

We can try to work around this issue, but it is not a priority right now.
