### ISSUE TITLE
Nuove serverInstance create da powershell NON si vedono in gordon

### ISSUE THREAD

**Issue by danielecacchiQGS** [EOS-Solutions/Gordon#91]
Gordon 1.0.162.0 (anche BARE aggiornato).
Installazione std BC240 (BC240_3) crea servizio BC240 che da gordon si vede
![image](https://github.com/user-attachments/assets/3fc1af3a-23b8-4e39-8153-565de2bb3672)

![image](https://github.com/user-attachments/assets/f917a315-7c64-41bf-b071-8946915b0364)

 

 

Se creo da powershell una nuova server instance chiamata BC240_1

![image](https://github.com/user-attachments/assets/ae1319e7-0a46-4ef8-b874-f586e34342c8)

 
E la avvio creando una webserver instance , riesco a collegarmi a BC
![image](https://github.com/user-attachments/assets/f5c84099-898d-49af-b9b1-e67e48b5ca5e)

 
Ma gordon non la fa vedere.
Cosa va a controllare gordon per poterla vedere?
In powershell con Get-NAVserverInstance , si cede:
![image](https://github.com/user-attachments/assets/e87adcd6-c493-4af7-9fd1-213f165d888f)

**Comment by f4n0** [comment]
Hai visto il ticket collegato? 
Il problema è lo stesso?

**Comment by Thomas-Torggler-EOS** [comment]
Closing as duplicate of #90
